server:
  port: 8071


mybatis:
  typeAliasesPackage: com.ey.dynamicrouter.entities
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    gateway:
      routes:
      - id: dynamicRouter
        uri: http://host
        predicates:
        - Path=/router/**
        filters:
        - Dynamic=/router
        - name: OrderedHystrix
          args:
            name: fallbackUri
            fallbackUri: forward:/index/hystrixFallback

hystrix.command.default.circuitBreaker.enabled: false